# Tor Instance 10
SocksPort 9268
ControlPort 9269
DataDirectory C:\laragon\www\Ddos\data\tor\tor10
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor10.log
