# Tor Instance 15
SocksPort 9278
ControlPort 9279
DataDirectory C:\laragon\www\Ddos\data\tor\tor15
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor15.log
