# Tor Instance 16
SocksPort 9280
ControlPort 9281
DataDirectory C:\laragon\www\Ddos\data\tor\tor16
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor16.log
