# Tor Instance 18
SocksPort 9284
ControlPort 9285
DataDirectory C:\laragon\www\Ddos\data\tor\tor18
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor18.log
