# Tor Instance 20
SocksPort 9288
ControlPort 9289
DataDirectory C:\laragon\www\Ddos\data\tor\tor20
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor20.log
