# Tor Instance 3
SocksPort 9254
ControlPort 9255
DataDirectory C:\laragon\www\Ddos\data\tor\tor3
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor3.log
