# Tor Instance 5
SocksPort 9258
ControlPort 9259
DataDirectory C:\laragon\www\Ddos\data\tor\tor5
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor5.log
