# Tor Instance 6
SocksPort 9260
ControlPort 9261
DataDirectory C:\laragon\www\Ddos\data\tor\tor6
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor6.log
