# Tor Instance 9
SocksPort 9266
ControlPort 9267
DataDirectory C:\laragon\www\Ddos\data\tor\tor9
CookieAuthentication 1

# Circuit rotation tuning
NewCircuitPeriod 30
MaxCircuitDirtiness 60

# Performance tuning
MaxClientCircuitsPending 64
UseEntryGuards 1
NumEntryGuards 8

# Logging
Log notice file logs\tor\tor9.log
